// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlrknksvvdgpiykuvhlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscmtua3N2dmRncGl5a3V2aGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDI3MjksImV4cCI6MjA3Mjk3ODcyOX0.lO1dQbzBFv1Jt6vUwkUhYH1Zf52liq614VHfyTTH1LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});